- hosts: servers
  vars:
    cryosparc_licenses:
      xxx.xxx.xxx.xxx: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
      xxx.xxx.xxx.xxx: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
      xxx.xxx.xxx.xxx: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
      xxx.xxx.xxx.xxx: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
      xxx.xxx.xxx.xxx: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
  tasks:
    - name: copy update_cryosparc_license script to remote machine
      become: yes
      become_user: scipion
      copy:
        src: /local/path/to/update_cryosparc_license.sh
        dest: /home/scipion/cryosparc4/update_cryosparc_license.sh
        mode: 0755

    - name: update cryosparc license
      become: yes
      become_user: scipion
      shell: "/home/scipion/cryosparc4/update_cryosparc_license.sh {{ cryosparc_licenses[inventory_hostname] }}"

    - name: warm up root disk
      become: yes
      shell: "tmux new-session -d -s warm_up_root_disk 'sudo fio --filename=/dev/nvme0n1p1 --rw=read --bs=128k --iodepth=32 --ioengine=libaio --direct=1 --name=volume-initialize'"

    - name: warm up data disk
      become: yes
      shell: "tmux new-session -d -s warm_up_data_disk 'sudo fio --filename=/dev/nvme1n1 --rw=read --bs=128k --iodepth=32 --ioengine=libaio --direct=1 --name=volume-initialize'"
